name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Asegúrate de que esta versión coincida con la que usas en tu proyecto

      - name: Install dependencies
        run: npm install
        working-directory: ./mi-proyecto  # Añade esta línea para especificar el directorio de trabajo

      - name: Build project
        run: npm run build
        working-directory: ./mi-proyecto  # Añade esta línea para especificar el directorio de trabajo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mi-proyecto/dist  # Asegúrate de que esta ruta coincida con la carpeta de salida de tu build